# Claude Code Hooks Configuration
# This file defines hooks that run automatically during Claude Code operations

# Pre-commit hook - runs before every git commit
[hooks.pre-commit]
name = "Format and Type Check"
description = "Runs code formatting and type checking before commits"
commands = [
    "pnpm format",
    "pnpm typecheck:all"
]
# If any command fails, the commit will be blocked
fail_on_error = true