# OpenTelemetry Collector configuration
# Simplified for development - basic functionality only

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - 'http://*'
            - 'https://*'

processors:
  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s

  # Batch processing for better throughput - smaller batches for testing
  batch:
    send_batch_size: 1
    send_batch_max_size: 10
    timeout: 1s

  # Resource detection
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: false

exporters:
  # OTLP exporter to our AI-native backend service
  otlphttp/backend:
    endpoint: http://backend:4319
    tls:
      insecure: true
    encoding: proto  # Use protobuf encoding (default)
    compression: gzip
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
    timeout: 30s

  # S3 exporters for raw OTLP capture (MinIO/S3 compatible) - FR-005a-002
  # Always defined - enable by uncommenting in pipeline exporters below
  awss3/traces:
    s3uploader:
      region: us-east-1
      s3_bucket: otel-data
      endpoint: http://minio:9000
      s3_force_path_style: true
      s3_prefix: continuous
      file_prefix: traces-
      compression: gzip

  awss3/metrics:
    s3uploader:
      region: us-east-1
      s3_bucket: otel-data
      endpoint: http://minio:9000
      s3_force_path_style: true
      s3_prefix: continuous
      file_prefix: metrics-
      compression: gzip

  awss3/logs:
    s3uploader:
      region: us-east-1
      s3_bucket: otel-data
      endpoint: http://minio:9000
      s3_force_path_style: true
      s3_prefix: continuous
      file_prefix: logs-
      compression: gzip

  # Debug exporter for development
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health

  # Performance profiling
  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [health_check, pprof]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlphttp/backend, awss3/traces, debug]
      # To disable S3 capture, change above line to: [otlphttp/backend, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlphttp/backend, awss3/metrics, debug]
      # To disable S3 capture, change above line to: [otlphttp/backend, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlphttp/backend, awss3/logs, debug]
      # To disable S3 capture, change above line to: [otlphttp/backend, debug]

  telemetry:
    logs:
      level: debug
