#!/bin/bash

# Sync Claude Code sessions to project-local directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLAUDE_SESSIONS_DIR="$PROJECT_ROOT/notes/claude-sessions"
CLAUDE_PROJECT_DIR="$HOME/.claude/projects/-Users-croach-projects-otel-ai"

echo "🔄 Syncing Claude Code Sessions to Project"
echo "==========================================="
echo ""

# Create project-local sessions directory
mkdir -p "$CLAUDE_SESSIONS_DIR"

if [ ! -d "$CLAUDE_PROJECT_DIR" ]; then
    echo "❌ No Claude sessions found for this project yet"
    echo "Claude sessions will appear after first Claude Code usage"
    exit 0
fi

echo "📁 Source: $CLAUDE_PROJECT_DIR"
echo "📁 Target: $CLAUDE_SESSIONS_DIR"
echo ""

# Generate consolidated HTML for all sessions
echo "🔄 Generating consolidated HTML transcript..."
claude-code-log "$CLAUDE_PROJECT_DIR" -o "$CLAUDE_SESSIONS_DIR/all-sessions.html" --no-individual-sessions

# Generate individual session HTMLs
echo "🔄 Generating individual session HTMLs..."  
claude-code-log "$CLAUDE_PROJECT_DIR" -o "$CLAUDE_SESSIONS_DIR/"

# Copy raw JSONL files for backup
echo "🔄 Copying JSONL session files..."
cp "$CLAUDE_PROJECT_DIR"/*.jsonl "$CLAUDE_SESSIONS_DIR/" 2>/dev/null || echo "⚠️  No JSONL files found"

# Generate session index
echo "🔄 Creating session index..."
cat > "$CLAUDE_SESSIONS_DIR/README.md" << 'EOF'
# Claude Code Sessions Archive

This directory contains archived Claude Code sessions for the otel-ai project.

## Files

- `all-sessions.html` - Consolidated view of all sessions
- `session-*.html` - Individual session transcripts  
- `*.jsonl` - Raw session data (backup)

## Viewing Sessions

Open any HTML file in your browser to view the conversations. The consolidated view shows all sessions in chronological order.

## Integration with Daily Notes

Key decisions and technical discussions from Claude sessions are summarized in the daily notes under:
- `notes/daily/YYYY.MM.DD.md` - Daily progress and session outcomes
- Each daily note includes a "Claude Code Session Archive" section

## Usage

Generated by `scripts/sync-claude-sessions.sh` - run this script to update the archive with latest sessions.

Last updated: $(date)
EOF

echo ""
echo "✅ Claude Code sessions synced successfully!"
echo ""
echo "📄 Available files:"
ls -la "$CLAUDE_SESSIONS_DIR" | grep -E '\.(html|jsonl|md)$'

echo ""
echo "🔍 To view sessions:"
echo "   open '$CLAUDE_SESSIONS_DIR/all-sessions.html'"
echo ""
echo "💡 Integration complete - sessions now stored locally with project"