name: Branch Protection & PR Requirements

on:
  schedule:
    # Check branch protection daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'check'
        type: choice
        options:
          - check
          - update
          - enforce

jobs:
  branch-protection-check:
    name: Verify Branch Protection Rules
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check branch protection status
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = 'main';
            
            console.log(`🔍 Checking branch protection for ${owner}/${repo}:${branch}`);
            
            try {
              const { data: protection } = await github.rest.repos.getBranchProtection({
                owner,
                repo,
                branch
              });
              
              console.log('✅ Branch protection is enabled');
              console.log('Current settings:');
              console.log(`- Require PR reviews: ${protection.required_pull_request_reviews ? 'Yes' : 'No'}`);
              console.log(`- Require status checks: ${protection.required_status_checks ? 'Yes' : 'No'}`);
              console.log(`- Enforce for admins: ${protection.enforce_admins.enabled}`);
              console.log(`- Allow force pushes: ${protection.allow_force_pushes.enabled}`);
              console.log(`- Allow deletions: ${protection.allow_deletions.enabled}`);
              
              if (protection.required_status_checks) {
                console.log('Required status checks:');
                protection.required_status_checks.contexts.forEach(check => {
                  console.log(`  - ${check}`);
                });
              }
              
            } catch (error) {
              console.log('⚠️ Branch protection not configured properly');
              console.log('Error:', error.message);
              
              if (error.status === 404) {
                console.log('❌ No branch protection rules found for main branch');
                core.setFailed('Branch protection must be configured for main branch');
              }
            }
            
      - name: Recommend protection settings
        run: |
          echo "🛡️ Recommended branch protection settings for main:"
          echo ""
          echo "Required settings:"
          echo "  ✅ Require pull request reviews before merging"
          echo "  ✅ Require status checks to pass before merging"
          echo "  ✅ Require branches to be up to date before merging"
          echo "  ✅ Include administrators"
          echo ""
          echo "Required status checks:"
          echo "  ✅ Quick Validation (never-break-main.yml)"
          echo "  ✅ Full Stack Testing (never-break-main.yml)"
          echo "  ✅ Security & Dependencies (never-break-main.yml)"
          echo "  ✅ Build & Deploy Readiness (never-break-main.yml)"
          echo "  ✅ Main Branch Protection Gate (never-break-main.yml)"
          echo ""
          echo "Optional but recommended:"
          echo "  🔒 Restrict pushes that create files larger than 100MB"
          echo "  🔒 Prevent force pushes"
          echo "  🔒 Prevent branch deletion"

  pr-requirements-check:
    name: Validate PR Requirements
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check PR requirements
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            console.log(`🔍 Checking PR #${pr.number} requirements`);
            
            let issues = [];
            
            // Check PR title format
            const titleRegex = /^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+/;
            if (!titleRegex.test(pr.title)) {
              issues.push('❌ PR title must follow conventional commit format: type(scope): description');
            } else {
              console.log('✅ PR title follows conventional commit format');
            }
            
            // Check PR description
            if (!pr.body || pr.body.trim().length < 50) {
              issues.push('❌ PR must have a meaningful description (minimum 50 characters)');
            } else {
              console.log('✅ PR has adequate description');
            }
            
            // Check branch name
            const branchRegex = /^(feat|fix|docs|style|refactor|test|chore)\/[a-z0-9-]+$/;
            if (!branchRegex.test(pr.head.ref)) {
              issues.push('❌ Branch name should follow pattern: type/description-with-hyphens');
            } else {
              console.log('✅ Branch name follows naming convention');
            }
            
            // Check if targeting main branch
            if (pr.base.ref !== 'main') {
              issues.push('❌ PR must target main branch');
            } else {
              console.log('✅ PR targets main branch');
            }
            
            // Check for draft status
            if (pr.draft) {
              console.log('ℹ️ PR is in draft status - requirements will be enforced when ready for review');
              return;
            }
            
            // Report issues
            if (issues.length > 0) {
              console.log('\n🚨 PR Requirements Issues:');
              issues.forEach(issue => console.log(issue));
              
              // Create or update comment with requirements
              const comment = `## 📋 PR Requirements Check
              
**Issues found:**
${issues.map(issue => `- ${issue}`).join('\n')}

**Requirements:**
- ✅ PR title: \`type(scope): description\` (e.g., \`feat(storage): add ClickHouse integration\`)
- ✅ Branch name: \`type/description-with-hyphens\` (e.g., \`feat/clickhouse-integration\`)
- ✅ Description: Meaningful description (minimum 50 characters)
- ✅ Target: Must target \`main\` branch
- ✅ All status checks must pass

Please fix these issues before the PR can be merged.`;
              
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr.number,
                body: comment
              });
              
              core.setFailed('PR does not meet requirements');
            } else {
              console.log('\n✅ All PR requirements met!');
            }