name: Reusable Quick Validation

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '20'
        type: string
      pnpm-version:
        description: 'PNPM version to use'
        required: false
        default: '8.15.0'
        type: string
      timeout-minutes:
        description: 'Timeout for the job in minutes'
        required: false
        default: 10
        type: number

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm-version }}
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: TypeScript compilation
        run: pnpm typecheck:all
        
      - name: Code quality (ESLint)
        run: pnpm lint
        
      - name: Code formatting (Prettier)
        run: pnpm format:check
        
      - name: Unit tests
        run: pnpm test