name: Sync Screenshots to GitHub Pages

on:
  push:
    branches: [main, test/ci-cd-validation]  # Added current branch for testing
    paths: ['notes/screenshots/**']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pages Structure
        run: |
          mkdir -p _site
          # Copy screenshots maintaining directory structure
          if [ -d "notes/screenshots" ]; then
            cp -r notes/screenshots _site/screenshots
          fi
          
          # Create simple index.html for navigation
          cat > _site/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>OTel AI Screenshots</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; margin: 40px; }
              h1 { color: #2563eb; }
              .date-folder { margin: 20px 0; }
              .date-folder h2 { color: #059669; margin: 10px 0; }
              .screenshot { margin: 10px 0; }
              .screenshot a { text-decoration: none; color: #7c3aed; }
              .screenshot a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>OTel AI Platform Screenshots</h1>
            <p>Automated screenshot hosting for blog posts, documentation, and external references.</p>
          EOF
          
          # Generate directory listing
          if [ -d "_site/screenshots" ]; then
            for date_dir in _site/screenshots/*/; do
              if [ -d "$date_dir" ]; then
                date_name=$(basename "$date_dir")
                echo "<div class='date-folder'>" >> _site/index.html
                echo "<h2>$date_name</h2>" >> _site/index.html
                for img in "$date_dir"*.png "$date_dir"*.jpg "$date_dir"*.jpeg; do
                  if [ -f "$img" ]; then
                    img_name=$(basename "$img")
                    echo "<div class='screenshot'><a href='screenshots/$date_name/$img_name'>$img_name</a></div>" >> _site/index.html
                  fi
                done
                echo "</div>" >> _site/index.html
              fi
            done
          fi
          
          echo "</body></html>" >> _site/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4